apiVersion: patch.bitspur.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  patches:
    - id: example
      target:
        version: v1
        kind: ConfigMap
        name: hello
      applyIf:
        - jsonPath: '{.spec}'
          regex: '.*'

      patch: |-
        data:
          howdy: texas

      # type: script
      # patch: |-
      #   echo Hello, world!

      # type: json
      # patch: |-
      #   - op: add
      #     path: /data/hello
      #     value: world

      # type: merge
      # patch: |-
      #   data:
      #     hello: world
