apiVersion: patch.bitspur.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  patches:
    - target:
        group: core
        version: v1
        kind: ConfigMap
        name: hello
        namespace: hello
      applyIf:
        - jsonPath: '{.spec}'
          regex: '.*'
      strategy: json
      patch: |
        hello: world
