apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tmp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
